import { Module2Config, Module2PresetId, ShelfTagItem, YellowPaletteId } from '../../types';

export interface PresetOption {
  id: Module2PresetId;
  name: string;
  dimensions: string;
  tagWidthMm: number;
  tagHeightMm: number;
  columns: number;
  rowGapMm: number;
  colGapMm: number;
  topMarginMm: number;
  sideMarginMm: number;
  description: string;
  badge: string;
}

export const SHELFTAG_PRESETS: PresetOption[] = [
  {
    id: 'standard',
    name: 'Standard Shelf Edge (3-Col)',
    dimensions: '65 × 42 mm',
    tagWidthMm: 65,
    tagHeightMm: 42,
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    description: '3 Columns × 6 Rows (18 tags/sheet on A4) - Perfect 3-column retail grocery shelf channel',
    badge: '18 tags/sheet',
  },
  {
    id: 'compact',
    name: 'Compact Strip Tag',
    dimensions: '54 × 32 mm',
    tagWidthMm: 54,
    tagHeightMm: 32,
    columns: 3,
    rowGapMm: 2.5,
    colGapMm: 3,
    topMarginMm: 8,
    sideMarginMm: 6,
    description: '3 Columns × 8 Rows (24 tags/sheet on A4) - High-density tag strip for tight shelves & cosmetics',
    badge: '24 tags/sheet',
  },
  {
    id: 'medium',
    name: 'Medium Price Point / Feature Tag',
    dimensions: '82 × 52 mm',
    tagWidthMm: 82,
    tagHeightMm: 52,
    columns: 2,
    rowGapMm: 4,
    colGapMm: 4,
    topMarginMm: 8,
    sideMarginMm: 8,
    description: '2 Columns × 5 Rows (10 tags/sheet on A4) - Noticeable mid-aisle promos, gondola heads & end-caps',
    badge: '10 tags/sheet',
  },
  {
    id: 'large',
    name: 'Large Talker / PP Tag',
    dimensions: '96 × 66 mm',
    tagWidthMm: 96,
    tagHeightMm: 66,
    columns: 2,
    rowGapMm: 5,
    colGapMm: 5,
    topMarginMm: 8,
    sideMarginMm: 8,
    description: '2 Columns × 4 Rows (8 tags/sheet on A4) - Big promotional standouts, display bins & pallets',
    badge: '8 tags/sheet',
  },
];

export interface YellowPaletteOption {
  id: YellowPaletteId;
  name: string;
  bgHex: string;
  borderHex: string;
  accentTextHex: string;
}

export const YELLOW_PALETTES: YellowPaletteOption[] = [
  {
    id: 'golden',
    name: 'Prince Golden Yellow',
    bgHex: '#FEED01',
    borderHex: '#000000',
    accentTextHex: '#dc2626',
  },
  {
    id: 'canary',
    name: 'Canary Yellow',
    bgHex: '#ffeb3b',
    borderHex: '#000000',
    accentTextHex: '#b91c1c',
  },
  {
    id: 'amber',
    name: 'Warm Amber',
    bgHex: '#f59e0b',
    borderHex: '#000000',
    accentTextHex: '#7f1d1d',
  },
  {
    id: 'lemon',
    name: 'Soft Lemon',
    bgHex: '#fef08a',
    borderHex: '#000000',
    accentTextHex: '#dc2626',
  },
];

export const DEFAULT_MODULE2_CONFIG: Module2Config = {
  presetId: 'standard',
  tagWidthMm: 65,
  tagHeightMm: 42,
  columns: 3,
  paperSize: 'A4',
  orientation: 'portrait',
  customWidthMm: 210,
  customHeightMm: 297,
  rowGapMm: 3,
  colGapMm: 2.5,
  topMarginMm: 8,
  bottomMarginMm: 8,
  sideMarginMm: 5,
  leftMarginMm: 5,
  rightMarginMm: 5,
  centerColumns: true,
  yellowPalette: 'golden',
  currencySymbol: '₱',
  barcodeFormat: 'CODE128',
  showStrikeThroughRegular: true,
  showCutGuides: true,
  showBorder: true,
  showLogo: true,
};

export const SAMPLE_SHELF_TAGS: ShelfTagItem[] = [
  {
    id: 'tag-1',
    tagStyle: 'white',
    description: 'COCA-COLA ORIGINAL TASTE 1.5L PET BOTTLE',
    sku: 'BEV-1001',
    barcode: '4800016644021',
    regularPrice: 72,
    promoPrice: null,
    unit: 'per BTL',
    locator: 'A01-01',
    category: 'Beverages',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-2',
    tagStyle: 'yellow',
    description: 'COCA-COLA ZERO SUGAR 1.5L PET BOTTLE',
    promoHeader: 'SAVE ₱13.00',
    promoSubtext: 'SAVE ₱13.00 • VALID UNTIL SEPT 30',
    promoValidity: 'Valid until Sept 30',
    sku: 'BEV-1002',
    barcode: '4800016644052',
    regularPrice: 78,
    promoPrice: 65,
    unit: 'per BTL',
    locator: 'A01-02',
    category: 'Beverages',
    isSelected: true,
    copies: 1,
  },
  {
    id: 'tag-3',
    tagStyle: 'yellow',
    description: 'SPAM CLASSIC LUNCHEON MEAT 340G CAN',
    promoHeader: 'HOT BUY ₱169',
    promoSubtext: 'SAVE ₱26.00 • HOT BUY SPECIAL',
    promoValidity: 'Special Promo Period',
    sku: 'CAN-2041',
    barcode: '037600104114',
    regularPrice: 195,
    promoPrice: 169,
    unit: 'per CAN',
    locator: 'B02-04',
    category: 'Canned Goods',
    isSelected: true,
    copies: 1,
  },
  {
    id: 'tag-4',
    tagStyle: 'yellow',
    description: 'NESCAFE CLASSIC INSTANT COFFEE JAR 200G',
    promoHeader: 'PROMO PRICE',
    promoSubtext: 'SAVE ₱30.00 • LIMITED TIME OFFER',
    promoValidity: 'Promo End: Sept 25',
    sku: 'COF-3012',
    barcode: '7613035862301',
    regularPrice: 215,
    promoPrice: 185,
    unit: 'per JAR',
    locator: 'C03-01',
    category: 'Coffee & Tea',
    isSelected: true,
    copies: 1,
  },
  {
    id: 'tag-5',
    tagStyle: 'white',
    description: 'SAN MIGUEL PALE PILSEN 330ML CAN',
    sku: 'BEV-1008',
    barcode: '4800028010012',
    regularPrice: 48,
    promoPrice: null,
    unit: 'per CAN',
    locator: 'A01-08',
    category: 'Beverages',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-6',
    tagStyle: 'white',
    description: 'CENTURY TUNA FLAKES IN OIL 180G',
    sku: 'CAN-2015',
    barcode: '748485100018',
    regularPrice: 38.5,
    promoPrice: null,
    unit: 'per CAN',
    locator: 'B01-12',
    category: 'Canned Goods',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-7',
    tagStyle: 'white',
    description: 'BEAR BRAND FORTIFIED POWDERED MILK 700G',
    sku: 'DAI-4022',
    barcode: '4800361280302',
    regularPrice: 260,
    promoPrice: null,
    unit: 'per PACK',
    locator: 'D01-05',
    category: 'Dairy & Milk',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-8',
    tagStyle: 'white',
    description: 'LUCKY ME! INSTANT PANCIT CANTON ORIGINAL 80G',
    sku: 'NOO-5001',
    barcode: '4800016052017',
    regularPrice: 15.5,
    promoPrice: null,
    unit: 'per PACK',
    locator: 'E02-03',
    category: 'Noodles',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-9',
    tagStyle: 'white',
    description: 'SAFEGUARD PURE WHITE SOAP 130G',
    sku: 'PC-6031',
    barcode: '4902430758413',
    regularPrice: 52,
    promoPrice: null,
    unit: 'per BAR',
    locator: 'F03-09',
    category: 'Personal Care',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-10',
    tagStyle: 'yellow',
    description: 'ARIEL SUNRISE FRESH POWDER DETERGENT 1.4KG',
    promoHeader: 'SPECIAL BUY',
    promoSubtext: 'SAVE ₱35.00 • WEEKEND SPECIAL',
    promoValidity: 'Valid until Sept 30',
    sku: 'DET-7019',
    barcode: '4902430689106',
    regularPrice: 225,
    promoPrice: 190,
    unit: 'per PACK',
    locator: 'G01-02',
    category: 'Household',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-11',
    tagStyle: 'yellow',
    description: 'JACK N JILL PIATTOS CHEESE 85G',
    promoHeader: 'BUY 2 SAVE MORE',
    promoSubtext: 'SAVE ₱6.00 • SNACK PROMO',
    promoValidity: 'Special Promo Period',
    sku: 'SNK-8014',
    barcode: '4800016641235',
    regularPrice: 38,
    promoPrice: 32,
    unit: 'per PACK',
    locator: 'H02-08',
    category: 'Snacks',
    isSelected: false,
    copies: 1,
  },
  {
    id: 'tag-12',
    tagStyle: 'yellow',
    description: 'TANG ORANGE POWDERED JUICE 25G 6S',
    promoHeader: 'PROMO PACK',
    promoSubtext: 'SAVE ₱12.00 • VALUE PACK',
    promoValidity: 'Promo End: Oct 15',
    sku: 'BEV-1045',
    barcode: '7622210871142',
    regularPrice: 96,
    promoPrice: 84,
    unit: 'per PACK',
    locator: 'A03-14',
    category: 'Beverages',
    isSelected: false,
    copies: 1,
  },
];
