import { Module2LayoutConfig, Module2TagType } from '../../types';

export const DEFAULT_SHELFTAG_CONFIG: Module2LayoutConfig = {
  presetId: 'standard',
  tagType: 'shelftag',
  paperSize: 'A4',
  customWidthMm: 210,
  customHeightMm: 297,
  orientation: 'portrait',
  columns: 3,
  tagWidthMm: 68,
  tagHeightMm: 42,
  marginTopMm: 8,
  marginBottomMm: 8,
  marginLeftMm: 6,
  marginRightMm: 6,
  topMarginMm: 8,
  sideMarginMm: 6,
  rowGapMm: 3,
  colGapMm: 3.5,
  gapRowMm: 3,
  gapColMm: 3.5,
  yellowPalette: 'golden',
  currencySymbol: '₱',
  barcodeFormat: 'CODE128',
  barcodeType: 'CODE128',
  barcodeHeightMm: 12,
  fontSizeTitle: 9.5,
  fontSizeSku: 8,
  fontSizeUpc: 8,
  fontSizePrice: 12,
  fontSizeLocator: 9,
  showStrikeThroughRegular: true,
  showBorder: true,
  showCutGuides: true,
  showLogo: true,
  logoUrl: '/prince-logo.svg',
  defaultCopies: 1,
};

export const DEFAULT_PPTAG_CONFIG: Module2LayoutConfig = {
  presetId: 'large',
  tagType: 'pp_tag',
  paperSize: 'A4',
  customWidthMm: 210,
  customHeightMm: 297,
  orientation: 'portrait',
  columns: 2,
  tagWidthMm: 96,
  tagHeightMm: 66,
  marginTopMm: 8,
  marginBottomMm: 8,
  marginLeftMm: 8,
  marginRightMm: 8,
  topMarginMm: 8,
  sideMarginMm: 8,
  rowGapMm: 5,
  colGapMm: 5,
  gapRowMm: 5,
  gapColMm: 5,
  yellowPalette: 'golden',
  currencySymbol: '₱',
  barcodeFormat: 'CODE128',
  barcodeType: 'CODE128',
  barcodeHeightMm: 14,
  fontSizeTitle: 10.5,
  fontSizeSku: 8.5,
  fontSizeUpc: 8.5,
  fontSizePrice: 14,
  fontSizeLocator: 10,
  showStrikeThroughRegular: true,
  showBorder: true,
  showCutGuides: true,
  showLogo: true,
  logoUrl: '/prince-logo.svg',
  defaultCopies: 1,
};

export function getDefaultModule2Config(tagType: Module2TagType): Module2LayoutConfig {
  return tagType === 'shelftag'
    ? { ...DEFAULT_SHELFTAG_CONFIG }
    : { ...DEFAULT_PPTAG_CONFIG };
}
