import { Module2TagType, TagFieldConfig, TagFieldId, TagLayoutPreset } from '../../types';

export const AVAILABLE_FONTS = [
  { id: 'Arial', name: 'Arial (Sans-serif)' },
  { id: 'Helvetica', name: 'Helvetica (Clean)' },
  { id: 'Times New Roman', name: 'Times New Roman (Serif)' },
  { id: 'Courier New', name: 'Courier New (Monospace)' },
  { id: 'Verdana', name: 'Verdana (Legible)' },
  { id: 'Georgia', name: 'Georgia (Serif)' },
  { id: 'Impact', name: 'Impact (Heavy Promo)' },
  { id: 'Trebuchet MS', name: 'Trebuchet MS' },
];

export interface TagFieldMeta {
  id: TagFieldId;
  label: string;
  category: 'text' | 'price' | 'barcode' | 'badge' | 'media';
  description: string;
}

export const ALL_TAG_FIELDS: TagFieldMeta[] = [
  { id: 'description', label: 'DESCRIPTION', category: 'text', description: 'Product title / trade description' },
  { id: 'sku', label: 'SKU / CODE', category: 'text', description: 'Stock keeping unit / product code' },
  { id: 'barcode', label: 'BARCODE', category: 'barcode', description: 'Scannable barcode & number' },
  { id: 'regularPrice', label: 'REGULAR PRICE', category: 'price', description: 'Retail price / WAS original price' },
  { id: 'promoPrice', label: 'PRICE PROMO', category: 'price', description: 'Special offer promotional price point' },
  { id: 'priceUnit', label: 'PRICE UNIT', category: 'price', description: 'Per piece, pack, or unit measurement' },
  { id: 'locator', label: 'LOCATOR', category: 'badge', description: 'Shelf aisle / bin location coordinate' },
  { id: 'promoHeader', label: 'PROMO HEADER', category: 'text', description: 'Top promotional banner bar (PP Tag)' },
  { id: 'logo', label: 'STORE LOGO', category: 'media', description: 'Prince store brand emblem' },
];

export function createDefaultFieldsForShelftag(tagWidthMm: number, tagHeightMm: number): Record<TagFieldId, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;
  const isCompact = w < 60;
  const isWide = w >= 90;

  return {
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 6 : 8.5,
      width: isWide ? w - 8 : w - 6,
      height: isCompact ? 9 : 11.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 7.5 : isWide ? 11 : 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 1.5 : 2.5,
      width: isWide ? 36 : 28,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 6.5 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      prefixText: 'SKU: ',
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: true,
      x: isWide ? 42 : 32,
      y: isCompact ? 1.5 : 2.5,
      width: isWide ? 22 : 16,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Courier New',
      fontSizePt: isCompact ? 6.5 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'solid',
      borderWidthPx: 1,
      borderRadiusMm: 0.5,
      borderColor: '#000000',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0.5,
      paddingRightMm: 0.5,
      locatorBadge: true,
    },
    barcode: {
      id: 'barcode',
      name: 'BARCODE',
      visible: true,
      x: isWide ? 4 : 3,
      y: isCompact ? 16 : 21,
      width: isWide ? 45 : Math.min(36, w * 0.52),
      height: isCompact ? 11 : 14.5,
      fontFamily: 'Courier New',
      fontSizePt: 6.5,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'left',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'left',
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'REGULAR PRICE',
      visible: true,
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 16 : 21,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: isCompact ? 9 : 12,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 11 : isWide ? 18 : 14.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      prefixText: 'RETAIL PRICE',
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: false, // White tag is regular
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 16 : 21,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: isCompact ? 9 : 11,
      fontFamily: 'Arial',
      fontSizePt: 13,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'PRICE UNIT',
      visible: true,
      x: isWide ? 52 : Math.max(34, w * 0.52),
      y: isCompact ? 26 : h - 7,
      width: isWide ? w - 56 : w - Math.max(34, w * 0.52) - 3,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isCompact ? 6 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: false,
      x: 0,
      y: 0,
      width: w,
      height: 6,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      backgroundColor: '#E31B23',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 2,
      paddingRightMm: 2,
    },
    logo: {
      id: 'logo',
      name: 'STORE LOGO',
      visible: true,
      x: w - 16,
      y: isCompact ? 1.5 : 2.5,
      width: 13,
      height: isCompact ? 3.8 : 4.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
  };
}

export function createDefaultFieldsForPPTag(tagWidthMm: number, tagHeightMm: number): Record<TagFieldId, TagFieldConfig> {
  const w = tagWidthMm;
  const h = tagHeightMm;
  const isLarge = w >= 80;
  const bannerH = Math.max(6.5, Math.round(h * 0.17));

  return {
    promoHeader: {
      id: 'promoHeader',
      name: 'PROMO HEADER',
      visible: true,
      x: 0,
      y: 0,
      width: w,
      height: bannerH,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 9.5 : 8,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      backgroundColor: '#E31B23',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 2.5,
      paddingRightMm: 2.5,
    },
    sku: {
      id: 'sku',
      name: 'SKU / CODE',
      visible: true,
      x: 3,
      y: bannerH + 1.5,
      width: isLarge ? 34 : 26,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 8.5 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      prefixText: 'SKU: ',
    },
    locator: {
      id: 'locator',
      name: 'LOCATOR',
      visible: true,
      x: isLarge ? 40 : 31,
      y: bannerH + 1.5,
      width: isLarge ? 20 : 15,
      height: 4.5,
      fontFamily: 'Courier New',
      fontSizePt: isLarge ? 8 : 7,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#ffffff',
      textAlign: 'center',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0.5,
      backgroundColor: '#000000',
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0.5,
      paddingRightMm: 0.5,
      locatorBadge: true,
    },
    logo: {
      id: 'logo',
      name: 'STORE LOGO',
      visible: true,
      x: w - 16,
      y: bannerH + 1.5,
      width: 13,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: 8,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    description: {
      id: 'description',
      name: 'DESCRIPTION',
      visible: true,
      x: 3,
      y: bannerH + 7,
      width: w - 6,
      height: isLarge ? 14 : 11,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 12 : 9.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'left',
      verticalAlign: 'top',
      textTransform: 'uppercase',
      textWrap: true,
      maxLines: 2,
      lineHeightPt: 11,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
    barcode: {
      id: 'barcode',
      name: 'BARCODE',
      visible: true,
      x: 3,
      y: isLarge ? h - 22 : h - 17,
      width: isLarge ? 46 : Math.min(35, w * 0.52),
      height: isLarge ? 18 : 13.5,
      fontFamily: 'Courier New',
      fontSizePt: 6.5,
      fontWeight: 'normal',
      fontStyle: 'normal',
      textDecoration: 'none',
      textAlign: 'left',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      barcodeFormat: 'CODE128',
      showBarcodeText: true,
      barcodeTextSizePt: 6.5,
      barcodeAlign: 'left',
    },
    regularPrice: {
      id: 'regularPrice',
      name: 'REGULAR PRICE',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: isLarge ? h - 21 : h - 16.5,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: 4.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 9 : 7.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
      strikeThrough: true,
      prefixText: 'WAS ',
    },
    promoPrice: {
      id: 'promoPrice',
      name: 'PRICE PROMO',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: isLarge ? h - 16.5 : h - 12,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: isLarge ? 11 : 8.5,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 19 : 14.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#E31B23',
      textAlign: 'right',
      verticalAlign: 'bottom',
      textTransform: 'none',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
      currencySymbol: '₱',
      showCurrencySymbol: true,
      decimalPlaces: 2,
    },
    priceUnit: {
      id: 'priceUnit',
      name: 'PRICE UNIT',
      visible: true,
      x: isLarge ? 52 : Math.max(34, w * 0.52),
      y: h - 5.5,
      width: isLarge ? w - 55 : w - Math.max(34, w * 0.52) - 3,
      height: 4,
      fontFamily: 'Arial',
      fontSizePt: isLarge ? 7.5 : 6.5,
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textColor: '#000000',
      textAlign: 'right',
      verticalAlign: 'middle',
      textTransform: 'uppercase',
      textWrap: false,
      maxLines: 1,
      borderStyle: 'none',
      borderWidthPx: 0,
      borderRadiusMm: 0,
      paddingTopMm: 0,
      paddingBottomMm: 0,
      paddingLeftMm: 0,
      paddingRightMm: 0,
    },
  };
}

// Built-in Presets for ShelfTag (White)
export const DEFAULT_SHELFTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'shelftag-std-65x42',
    name: 'Standard Shelf Edge (3-Col)',
    tagType: 'shelftag',
    description: '65 × 42 mm • 3 Cols × 6 Rows (18 tags/A4) - Perfect 3-column retail shelf channel',
    isBuiltIn: true,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(65, 42),
  },
  {
    id: 'shelftag-compact-54x32',
    name: 'Compact Strip Tag',
    tagType: 'shelftag',
    description: '54 × 32 mm • 3 Cols × 8 Rows (24 tags/A4) - High density for tight cosmetic shelves',
    isBuiltIn: true,
    tagWidthMm: 54,
    tagHeightMm: 32,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 2.5,
    colGapMm: 3,
    topMarginMm: 8,
    sideMarginMm: 6,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(54, 32),
  },
  {
    id: 'shelftag-wide-100x50',
    name: 'Standard Wide ShelfTag',
    tagType: 'shelftag',
    description: '100 × 50 mm • 2 Cols × 5 Rows (10 tags/A4) - Generous wide format with big text',
    isBuiltIn: true,
    tagWidthMm: 100,
    tagHeightMm: 50,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 5,
    topMarginMm: 10,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    fields: createDefaultFieldsForShelftag(100, 50),
  },
];

// Built-in Presets for PP Tag (Yellow / Promo)
export const DEFAULT_PPTAG_PRESETS: TagLayoutPreset[] = [
  {
    id: 'pptag-std-65x42',
    name: 'Standard PP Promo Tag (3-Col)',
    tagType: 'pp_tag',
    description: '65 × 42 mm • 3 Cols × 6 Rows (18 tags/A4) - Perfect 3-column high-visibility yellow promo',
    isBuiltIn: true,
    tagWidthMm: 65,
    tagHeightMm: 42,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 3,
    rowGapMm: 3,
    colGapMm: 2.5,
    topMarginMm: 8,
    sideMarginMm: 5,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'SPECIAL BUY',
    fields: createDefaultFieldsForPPTag(65, 42),
  },
  {
    id: 'pptag-feature-82x52',
    name: 'Medium Feature / Price Point',
    tagType: 'pp_tag',
    description: '82 × 52 mm • 2 Cols × 5 Rows (10 tags/A4) - Eye-catching mid-aisle & gondola end-caps',
    isBuiltIn: true,
    tagWidthMm: 82,
    tagHeightMm: 52,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 4,
    colGapMm: 4,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'PROMO TAG',
    fields: createDefaultFieldsForPPTag(82, 52),
  },
  {
    id: 'pptag-talker-96x66',
    name: 'Large Talker / PP Tag',
    tagType: 'pp_tag',
    description: '96 × 66 mm • 2 Cols × 4 Rows (8 tags/A4) - Giant promotional standout for pallet bins',
    isBuiltIn: true,
    tagWidthMm: 96,
    tagHeightMm: 66,
    paperSize: 'A4',
    orientation: 'portrait',
    columns: 2,
    rowGapMm: 5,
    colGapMm: 5,
    topMarginMm: 8,
    sideMarginMm: 8,
    yellowPalette: 'golden',
    currencySymbol: '₱',
    showBorder: true,
    showCutGuides: true,
    showLogo: true,
    promoHeader: 'SUPER SAVINGS',
    fields: createDefaultFieldsForPPTag(96, 66),
  },
];

// Local Storage Keys
export const STORAGE_SHELFTAG_PRESETS_KEY = 'prg_shelftag_presets_v2';
export const STORAGE_PPTAG_PRESETS_KEY = 'prg_pptag_presets_v2';
export const STORAGE_ACTIVE_SHELFTAG_ID_KEY = 'prg_active_shelftag_preset_id_v2';
export const STORAGE_ACTIVE_PPTAG_ID_KEY = 'prg_active_pptag_preset_id_v2';

export function loadPresetsFromStorage(tagType: Module2TagType, fallback?: TagLayoutPreset[]): TagLayoutPreset[] {
  const key = tagType === 'shelftag' ? STORAGE_SHELFTAG_PRESETS_KEY : STORAGE_PPTAG_PRESETS_KEY;
  const defaults = fallback || (tagType === 'shelftag' ? DEFAULT_SHELFTAG_PRESETS : DEFAULT_PPTAG_PRESETS);

  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaults;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
  } catch (e) {
    console.warn('Failed to parse presets from storage', e);
  }
  return defaults;
}

export function savePresetsToStorage(tagType: Module2TagType, presets: TagLayoutPreset[]): void {
  const key = tagType === 'shelftag' ? STORAGE_SHELFTAG_PRESETS_KEY : STORAGE_PPTAG_PRESETS_KEY;
  try {
    localStorage.setItem(key, JSON.stringify(presets));
  } catch (e) {
    console.warn('Failed to save presets to storage', e);
  }
}

export function saveActivePreset(tagType: Module2TagType, presetId: string): void {
  const key = tagType === 'shelftag' ? STORAGE_ACTIVE_SHELFTAG_ID_KEY : STORAGE_ACTIVE_PPTAG_ID_KEY;
  try {
    localStorage.setItem(key, presetId);
  } catch (e) {
    console.warn('Failed to save active preset id', e);
  }
}

export function loadActivePresetId(tagType: Module2TagType): string | null {
  const key = tagType === 'shelftag' ? STORAGE_ACTIVE_SHELFTAG_ID_KEY : STORAGE_ACTIVE_PPTAG_ID_KEY;
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}
